// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnJJNkOqElfGmwAChZhRrDrro4J-t9otY',
    appId: '1:232174777876:web:a2f8f641f2b382949f5901',
    messagingSenderId: '232174777876',
    projectId: 'chatappflut-62c9f',
    authDomain: 'chatappflut-62c9f.firebaseapp.com',
    storageBucket: 'chatappflut-62c9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLMWjAVkQJruWoxqKP-n2JNqKR5dx3XU4',
    appId: '1:232174777876:android:66e9ecaa066804559f5901',
    messagingSenderId: '232174777876',
    projectId: 'chatappflut-62c9f',
    storageBucket: 'chatappflut-62c9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSu-Y8W1Z6de3a7lOnJwLO9z2otn-dxQk',
    appId: '1:232174777876:ios:7ead17df698738979f5901',
    messagingSenderId: '232174777876',
    projectId: 'chatappflut-62c9f',
    storageBucket: 'chatappflut-62c9f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSu-Y8W1Z6de3a7lOnJwLO9z2otn-dxQk',
    appId: '1:232174777876:ios:f79db9513b3848cd9f5901',
    messagingSenderId: '232174777876',
    projectId: 'chatappflut-62c9f',
    storageBucket: 'chatappflut-62c9f.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
